pipeline:
  build:
    image: golang:${GO_VERSION}-alpine
    commands:
      - apk --update add git
      - go get -t -d -v
      - go build
      - go test -v -cover
workspace:
  base: /go
matrix:
  GO_VERSION:
    - 1.5.4
    - 1.6.3
