pipeline:
  build:
    image: appleboy/golang-testing
    pull: true
    environment:
      - GOPATH=/go
    commands:
      - glide install
      - coverage all

  notify:
    image: appleboy/drone-slack
    channel: jenkins
    username: drone
    when:
      status: [ success, failure ]
    template: |
      *{{ build.status }}* <{{ build.link }}|{{ repo.owner }}/{{ repo.name }}#{{ truncate build.commit 8 }}> ({{ build.branch }}) by {{ build.author }}.
    image_url: https://cdn3.iconfinder.com/data/icons/picons-social/57/16-apple-128.png

  slack:
    channel: drone
    username: drone
    when:
      status: [ killed, success, failure ]
    template: |
      *{{ build.status }}* <{{ build.link }}|{{ repo.owner }}/{{ repo.name }}#{{ truncate build.commit 8 }}> ({{ build.branch }}) by {{ build.author }}.

workspace:
  path: /go/src/github.com/appleboy/go-hello
