pipeline:
  build:
    image: appleboy/golang-testing
    environment:
      - GOPATH=/go
    commands:
      - glide install
      - coverage all

workspace:
  path: /go/src/github.com/appleboy/go-hello
