pipeline:
  # restore the cache from an sftp server
  restore_cache:
    image: appleboy/drone-sftp-cache
    restore: true
    mount: [ .glide, vendor ]
    ignore_branch: true

  build:
    image: appleboy/golang-testing:${GO_VERSION}
    pull: true
    environment:
      - GOPATH=/go
    commands:
      - glide install
      - coverage all

  notify_1:
    pull: true
    image: plugins/slack
    channel: jenkins
    username: drone
    when:
      status: [ success, failure ]
    template: >
      {{#success build.status}}
        {{ build.author }} successfully pushed to {{ build.branch}}
      {{else}}
        {{ build.author }} broke the build. Hang your head in shame.
      {{/success}}
    image_url: https://cdn3.iconfinder.com/data/icons/picons-social/57/16-apple-128.png

  notify_2:
    pull: true
    image: plugins/slack
    channel: drone
    username: drone
    when:
      status: [ success, failure ]
    template: |
      {{#success build.status}}
        {{ build.author }} successfully pushed to {{ build.branch}}
      {{else}}
        {{ build.author }} broke the build. Hang your head in shame.
      {{/success}}

  slack:
    image: plugins/slack
    channel: drone
    username: drone
    when:
      status: [ killed, success, failure ]
    template: |
      *{{ build.status }}* <{{ build.link }}|{{ repo.owner }}/{{ repo.name }}#{{ truncate build.commit 8 }}> ({{ build.branch }}) by {{ build.author }}.
    icon_url: https://cdn3.iconfinder.com/data/icons/picons-social/57/16-apple-128.png

  line:
    image: appleboy/drone-line
    pull: true
    to: u359650f919427b5229330c7205c47ee4
    when:
      status: [ success, failure ]
      matrix:
        GO_VERSION: 1.7.3

  facebook:
    image: appleboy/drone-facebook
    pull: true
    to: 1234973386524610
    when:
      status: [ success, failure ]
      matrix:
        GO_VERSION: 1.7.3

  gtalk:
    image: appleboy/drone-gtalk
    pull: true
    to:
      - appleboy.tw@gmail.com:appleboy.tw@gmail.com
      - appleboy.tw@gmail.com:test@gmail.com
    when:
      status: [ success, failure ]
      matrix:
        GO_VERSION: 1.7.3

  telegram_1:
    image: appleboy/drone-telegram
    pull: true
    to: 65382999:appleboy.tw@gmail.com
    when:
      status: [ success, failure ]
      matrix:
        GO_VERSION: 1.7.3

  telegram_2:
    image: appleboy/drone-telegram
    pull: true
    only_match_email: true
    to:
      - 65382999:appleboy.tw@gmail.com
      - 65382999
    message: "Please don't send duplicate of message"
    when:
      status: [ success, failure ]
      matrix:
        GO_VERSION: 1.7.3

  # rebuild the cache on the sftp server
  rebuild_cache:
    image: appleboy/drone-sftp-cache
    rebuild: true
    mount: [ .glide, vendor ]
    ignore_branch: true
    when:
      branch: master
      matrix:
        GO_VERSION: 1.7.3

workspace:
  path: /go/src/github.com/appleboy/go-hello

matrix:
  GO_VERSION:
    - 1.7.3
    - 1.6.3
