build:
  image: golang:1.6
  commands:
    - go get golang.org/x/tools/cmd/cover
    - go get github.com/mattn/goveralls
    - go get ./...
    - make test
    - go test -v -covermode=count -coverprofile=coverage.out
