sudo: required

language: go

services:
  - docker

env:
  global:
   - secure: "KS1xIWNQ0cIbR1BN99sUfgR3PpCjn1ETyB5lesDLNEpWqUv3ThFWgo3MV7cLuP+EIQ4+MIWpmKZxRyILcS1pyhZc9/9Kn7+i8AQSC0mXUai5QWq+rdMH6owi0OHficpRURhcwD5YggE2mS8yLqLeET493deIuUjUV91N7N7tu8U="

go:
  - 1.3
  - 1.4
  - 1.5
  - tip

before_install:
  - make all

install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls

script:
  - curl http://127.0.0.1:8000
  - make test
  - go test -v -covermode=count -coverprofile=coverage.out
  - $(go env GOPATH | awk 'BEGIN{FS=":"} {print $1}')/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN
