sudo: required
language: go

services:
  - docker

go:
  - 1.5
  - 1.6
  - 1.6.3
  - tip

env:
  global:
    secure: jeSgPztK8ytfBEBlZiswBIjXd1dafyLwERpFXYX+AYm31/I8kq3AOOEEGIGHD8ITHoc9/QFgvb2X7x/3c9csLZ1qYp8OF0kP7fCP3pQc5PA0mO1sBGKEEtv5Rmosw2yBwf4TCdbX1CMumbskWGyrJIJpGVILeCmGJhIx1UjY9vEnGkfz5feAnqu23sEDfIGWIuUol79J+Q/CsBbLl/H8JsMetC0XM2lRLrU+1iKKze2HHhLev7WIswwlI374NDWwRW8EuQUUiY9TqEHB0YIqHMK3DuFG8hXB9AiVOOKQRQ1uMuFMVtY6eXYEMefuCpl4zB8mFe0+BwKGcC9DZN8rOUSrSH8JCK718P1Fn6QsAtPcsX3tiZ6VVYifluH69SyliGO07Hg6d4SzrXUqTAJLhOoyy8FZMC7hOxX3Lg/hWWjlMVu8987GkLC6E7vbY8stu2VLbRLZZ1wNNHuBr/jg/6+CIztNdBbRtW9ePVGA30eD+H9maXz4KuJ7PZB3eJfk6wDLl7Wqq+WR1R536E6WeoxL3lEeATHJjwanCTrVjbS1GVv+8DDFsoJnA8aIDvYSnEJjyFH4aVMxjo2IWUA3jeGOib7mUk+qC2VU3HsfVQP2E/Cu/TnLai4cXYUoRHNB69k2LVULNxha9350HJO9SF4T2yqjEHzRuRQGoSH7y4A=

before_install:
  - make all
  - test -d $GOPATH/bin || mkdir -p $GOPATH/bin
  - curl https://glide.sh/get | sh

install:
  - export GO15VENDOREXPERIMENT=1
  - glide install
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls

script:
  - make test
  - go test -v -covermode=count -coverprofile=coverage.out
  - $(go env GOPATH | awk 'BEGIN{FS=":"} {print $1}')/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken=$COVERALLS_TOKEN

after_success:
  - bash <(curl -s https://codecov.io/bash)
