sudo: required
language: go

services:
  - docker

go:
  - 1.5
  - 1.6
  - 1.6.3
  - 1.7
  - tip

env:
  global:
    - DOCKER_COMPOSE_VERSION=1.8.0
    - secure: jeSgPztK8ytfBEBlZiswBIjXd1dafyLwERpFXYX+AYm31/I8kq3AOOEEGIGHD8ITHoc9/QFgvb2X7x/3c9csLZ1qYp8OF0kP7fCP3pQc5PA0mO1sBGKEEtv5Rmosw2yBwf4TCdbX1CMumbskWGyrJIJpGVILeCmGJhIx1UjY9vEnGkfz5feAnqu23sEDfIGWIuUol79J+Q/CsBbLl/H8JsMetC0XM2lRLrU+1iKKze2HHhLev7WIswwlI374NDWwRW8EuQUUiY9TqEHB0YIqHMK3DuFG8hXB9AiVOOKQRQ1uMuFMVtY6eXYEMefuCpl4zB8mFe0+BwKGcC9DZN8rOUSrSH8JCK718P1Fn6QsAtPcsX3tiZ6VVYifluH69SyliGO07Hg6d4SzrXUqTAJLhOoyy8FZMC7hOxX3Lg/hWWjlMVu8987GkLC6E7vbY8stu2VLbRLZZ1wNNHuBr/jg/6+CIztNdBbRtW9ePVGA30eD+H9maXz4KuJ7PZB3eJfk6wDLl7Wqq+WR1R536E6WeoxL3lEeATHJjwanCTrVjbS1GVv+8DDFsoJnA8aIDvYSnEJjyFH4aVMxjo2IWUA3jeGOib7mUk+qC2VU3HsfVQP2E/Cu/TnLai4cXYUoRHNB69k2LVULNxha9350HJO9SF4T2yqjEHzRuRQGoSH7y4A=

before_install:
  - sudo apt-get -y update
  - sudo apt-get -y purge docker-engine
  - sudo apt-get -y install docker-engine
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

install:
  - export GO15VENDOREXPERIMENT=1
  - go get github.com/mattn/goveralls

script:
  - make test
  - make docker_test
  - make docker_compose_test
  - $(go env GOPATH | awk 'BEGIN{FS=":"} {print $1}')/bin/goveralls -coverprofile=.cover/coverage.txt -service=travis-ci -repotoken=$COVERALLS_TOKEN

after_success:
  - bash <(curl -s https://codecov.io/bash) -f .cover/coverage.txt
